project_id = "onucizagpgwdpcakskat"

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-create-worker]
verify_jwt = true

[functions.send-quotation-email]
verify_jwt = true

[functions.generate-quotation-pdf]
verify_jwt = true