-- Create default users with specific credentials
-- First, let's insert into auth.users (this will trigger the profile creation)

-- Insert admin user
INSERT INTO auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_sent_at,
  recovery_token,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  confirmed_at,
  email_change_token_current_deadline,
  email_change_token_new_deadline,
  is_anonymous,
  sso_providers
) VALUES (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'gavaskar@gmail.com',
  crypt('123456789', gen_salt('bf')),
  now(),
  now(),
  '',
  null,
  '',
  '',
  '',
  null,
  '',
  0,
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"name": "Admin User", "role": "admin"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  now(),
  null,
  null,
  false,
  ARRAY[]::text[]
) ON CONFLICT (email) DO NOTHING;

-- Insert worker user
INSERT INTO auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_sent_at,
  recovery_token,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  confirmed_at,
  email_change_token_current_deadline,
  email_change_token_new_deadline,
  is_anonymous,
  sso_providers
) VALUES (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'worker1@gmail.com',
  crypt('123456789', gen_salt('bf')),
  now(),
  now(),
  '',
  null,
  '',
  '',
  '',
  null,
  '',
  0,
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"name": "Worker User", "role": "worker"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  now(),
  null,
  null,
  false,
  ARRAY[]::text[]
) ON CONFLICT (email) DO NOTHING;

-- Now manually insert profiles since the trigger might not work with manual inserts
INSERT INTO public.profiles (id, name, email, role) 
SELECT 
  u.id,
  CASE 
    WHEN u.email = 'gavaskar@gmail.com' THEN 'Admin User'
    WHEN u.email = 'worker1@gmail.com' THEN 'Worker User'
  END as name,
  u.email,
  CASE 
    WHEN u.email = 'gavaskar@gmail.com' THEN 'admin'::user_role
    WHEN u.email = 'worker1@gmail.com' THEN 'worker'::user_role
  END as role
FROM auth.users u 
WHERE u.email IN ('gavaskar@gmail.com', 'worker1@gmail.com')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  role = EXCLUDED.role;