// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eipnkhndgtksqhhizoqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpcG5raG5kZ3Rrc3FoaGl6b3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NzU4NTIsImV4cCI6MjA2NjE1MTg1Mn0.NJWel2NBWyjonkX7U2-ltA6DOXEzl7TnEQz1AYQNV94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);